PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE `Academic_Year` (
	`academic_year` YEAR,
	PRIMARY KEY (`academic_year`)
);
INSERT INTO Academic_Year VALUES(1994);
INSERT INTO Academic_Year VALUES(2007);
INSERT INTO Academic_Year VALUES(1985);
INSERT INTO Academic_Year VALUES(2002);
INSERT INTO Academic_Year VALUES(2009);
INSERT INTO Academic_Year VALUES(1995);
INSERT INTO Academic_Year VALUES(1997);
INSERT INTO Academic_Year VALUES(1992);
INSERT INTO Academic_Year VALUES(1998);
INSERT INTO Academic_Year VALUES(2000);
INSERT INTO Academic_Year VALUES(2004);
INSERT INTO Academic_Year VALUES(2006);
INSERT INTO Academic_Year VALUES(1987);
INSERT INTO Academic_Year VALUES(2010);
INSERT INTO Academic_Year VALUES(2011);
INSERT INTO Academic_Year VALUES(2012);
INSERT INTO Academic_Year VALUES(1996);
INSERT INTO Academic_Year VALUES(2005);
INSERT INTO Academic_Year VALUES(1991);
INSERT INTO Academic_Year VALUES(1969);
INSERT INTO Academic_Year VALUES(1993);
INSERT INTO Academic_Year VALUES(2003);
INSERT INTO Academic_Year VALUES(1989);
INSERT INTO Academic_Year VALUES(1999);
INSERT INTO Academic_Year VALUES(2001);
INSERT INTO Academic_Year VALUES(1986);
INSERT INTO Academic_Year VALUES(2008);
INSERT INTO Academic_Year VALUES(1956);
INSERT INTO Academic_Year VALUES(1966);
COMMIT;
